MACHINE: GPU2 #MAC #CPU # "NPU", "MAC"
MODEL: VGG19
PRETRAINED: True

RESUME: False
RESUME_TIMESTAMP: 2023-08-06_22-42-10
RESUME_SUMMARY_NAME: VGG19_clean_2023-08-06_22-42-10
RESUME_MODEL: models/LAST_VGG19_clean_2023-08-06_22-42-10.pth
RESUME_EPOCH: 100

INIT_LR: 0.00005
BATCH_SIZE:  32
EPOCHS: 50

TRAIN_SPLIT: 0.80

NUM_CLASSES: 8
NUM_CHANNELS: 3
DROPOUT_P: 0.7


SUMMARY_NAME: VGG19_pre
SUMMARY_COMMENT: VGG19 on shape catalogue, pretraining (the correct one)
IMAGE_DIR_PATH:  C:\Users\lhartz\datasets\InstanceRotation\TrainShapeCatalog
LABEL_FILE_PATH: C:\Users\lhartz\datasets\InstanceRotation\labels.csv
# MODEL_SAVE_PATH: U:\piresearchStudentsShared\Linus_Hartz\08_Models\SymbolOrientation\models
BASE_PATH: C:\Users\lhartz\TrainData
